version: '3.1'

services:

  db:
    image: mysql
    container_name: mysql_test13
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql_data13:/var/lib/mysql
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: example
    networks:
      - mylan

  admin:
    image: phpmyadmin
    container_name: phpmyadmin_test13
    networks:
      - mylan

    environment:
      - PMA_HOST=mysql_test13
      - PMA_USER=root
      - PMA_PASSWORD=example
    depends_on:
      - db
    ports:
      - 8090:80

  tool:
    image: busybox
    container_name: busybox_test13
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    networks:
      - mylan

  # myapp:
  #   build: ./
  #   image: my_app_img


volumes:
  mysql_data13:
networks:
  mylan:
