version: '3.1'

services:

  db:
    image: mysql
    container_name: mysql1
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: example

  admin:
    image: phpmyadmin
    environment:
      - PMA_HOST=mysql1
      - PMA_USER=root
      - PMA_PASSWORD=example
    depends_on:
      - db
    ports:
      - 8090:80
